name: Web Deployment

on:
  push:
    branches:
      - 'main'
    paths:
        - 'apps/web/**'

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2

      - name: Install Dependencies
        run: bun install

      - run: bun run build --filter=web
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_CLOUDFLARE_TURNSTILE_SITE_KEY }}

      - name: Deploy
        uses: AdrianGonz97/refined-cf-pages-action@6f7dc14a750d860b899996c827c94925b798cb38 # v1.2.6
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: instant-postgres
          directory: ./build/client
          workingDirectory: ./apps/web
          deploymentName: web
          branch: main