name: Preview Deployment
on: [pull_request]

env:
  COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
  INSTANT_POSTGRES_API_KEY: ${{ secrets.INSTANT_POSTGRES_API_KEY }}
  CLOUDFLARE_TURNSTILE_SECRET_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}
  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }} # Required for commenting on pull requests for private repos
  VITE_CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_CLOUDFLARE_TURNSTILE_SITE_KEY }}
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
  
jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2

      - name: Install Dependencies
        run: bun install

      - name: Get git branch name
        id: branch-name
        uses: tj-actions/branch-names@6871f53176ad61624f978536bbf089c574dc19a2 # v8.0.1


      - id: create-branch
        uses: neondatabase/create-branch-action@34f619c41c6e67b4f2f13f1c6eae90827a5f2cf4 # v5
        with:
          project_id: delicate-smoke-42060837
          username: "neondb_owner" # Change this to the role you use to connect to your database
          # parent: dev # optional (defaults to your primary branch)
          branch_name: preview/${{ steps.branch-name.outputs.current_branch }}
          api_key: ${{ secrets.NEON_API_KEY }} # Generate an API key in your Neon account settings
  
      - run: bun run turbo db:migrate
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url_with_pooler }}

      - run: bun run build --filter=api
        env:
          DATABASE_URL: ${{ steps.create-branch.outputs.db_url_with_pooler }}
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          INSTANT_POSTGRES_API_KEY: ${{ secrets.INSTANT_POSTGRES_API_KEY }}
          APP_URL: https://${{ steps.branch-name.outputs.current_branch }}.instant-postgres.pages.dev
          CLOUDFLARE_TURNSTILE_SECRET_KEY: ${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

      - name: Deploy API
        uses: AdrianGonz97/refined-cf-pages-action@6f7dc14a750d860b899996c827c94925b798cb38 # v1.2.6
        id: deploy-api
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: instant-postgres-api
          directory: ./dist
          workingDirectory: ./apps/api
          deploymentName: ${{ steps.branch-name.outputs.current_branch }}
          branch: ${{ steps.branch-name.outputs.current_branch }}

      - run: bun run build --filter=web
        env:
          VITE_API_URL: https://${{ steps.branch-name.outputs.current_branch }}.instant-postgres-api.pages.dev
          VITE_CLOUDFLARE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_CLOUDFLARE_TURNSTILE_SITE_KEY }}

      - name: Deploy Web
        id: deploy-web
        uses: AdrianGonz97/refined-cf-pages-action@6f7dc14a750d860b899996c827c94925b798cb38 # v1.2.6
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: instant-postgres
          directory: ./build/client
          workingDirectory: ./apps/web
          deploymentName: ${{ steps.branch-name.outputs.current_branch }}
          branch: ${{ steps.branch-name.outputs.current_branch }}
